os: Visual Studio 2017
platform:
- Any CPU
skip_branch_with_pr: true
configuration:
- Release
before_build:
- cmd: >-
    dotnet restore
build_script:
  - dotnet build -c %CONFIGURATION%
test_script:
  - dotnet test "MarkConv.Tests\MarkConv.Tests.csproj" -c %CONFIGURATION%