image:
- Visual Studio 2019
- Ubuntu
version: 0.0.0.{build}
configuration: Release
skip_branch_with_pr: true
assembly_info:
  patch: true
  file: AssemblyInfoCommon.cs;
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build_script:
- ps: |
    dotnet build -c Release

    dotnet publish MarkConv.Cli/MarkConv.Cli.csproj -c Release -o ../bin/netcoreapp3.1 -f netcoreapp3.1
test_script:
  - dotnet test "MarkConv.Tests/MarkConv.Tests.csproj" -c Release
after_test:
- ps: |
    cd bin/netcoreapp3.1

    7z a MarkConv-netcoreapp3.1-$env:APPVEYOR_BUILD_VERSION.zip *.dll *.config *.json runtimes

    Push-AppveyorArtifact MarkConv-netcoreapp3.1-$env:APPVEYOR_BUILD_VERSION.zip